Repository Centiq/sap-hana, pull requests merged in 2020-12, with the labels that each got.

#61 Doc updates to correct multiple issues
  documentation/ansible/system-design-deployment/app/prepare-bom.md
  documentation/ansible/system-design-deployment/app/prepare-full-app-bom.md
  documentation/ansible/system-design-deployment/app/prepare-ini.md
  documentation/ansible/system-design-deployment/app/prepare-system.md
  documentation/ansible/system-design-deployment/examples/BW4HANA_2_0_v001/bom.yml
  documentation/ansible/system-design-deployment/examples/HANA_1_00_122_v001/bom.yml
  documentation/ansible/system-design-deployment/examples/HANA_2_00_052_v001/bom.yml
  documentation/ansible/system-design-deployment/examples/S4HANA_1909_SP2_v001/bom.yml
  documentation/ansible/system-design-deployment/examples/S4HANA_2020_ISS_v001/bom.yml
  documentation/ansible/system-design-deployment/hana/prepare-bom.md
  documentation/ansible/system-design-deployment/hana/prepare-ini.md
  documentation/ansible/system-design-deployment/hana/prepare-system.md
Labels: enhancement

#64 Update inifile Consolidation instructions
  documentation/ansible/system-design-deployment/app/prepare-ini.md
  documentation/ansible/system-design-deployment/examples/S4HANA_1809_SP5_v001/S4HANA_1809_SP5_v001.inifile.params
  documentation/ansible/system-design-deployment/examples/S4HANA_1809_SP5_v001/bom.yml
  documentation/ansible/system-design-deployment/examples/S4HANA_1809_SP5_v001/stackfiles/MP_Excel_1001080495_20201123_SWC.xls
  documentation/ansible/system-design-deployment/examples/S4HANA_1809_SP5_v001/stackfiles/MP_Plan_1001080495_20201123_.pdf
  documentation/ansible/system-design-deployment/examples/S4HANA_1809_SP5_v001/stackfiles/MP_Stack_1001080495_20201123_.txt
  documentation/ansible/system-design-deployment/examples/S4HANA_1809_SP5_v001/stackfiles/MP_Stack_1001080495_20201123_.xml
  documentation/ansible/system-design-deployment/examples/S4HANA_1809_SP5_v001/stackfiles/downloadbasket.json
Labels: enhancement

#66 Scs unattended install
  deploy/ansible/poc_bom_iteration_playbook.yml
  deploy/ansible/roles/process_bom/tasks/configure_disk.yml
  deploy/ansible/roles/scs-install/defaults/main.yml
  deploy/ansible/roles/scs-install/tasks/install_scs.yml
  deploy/ansible/roles/scs-install/tasks/main.yml
  deploy/ansible/roles/scs-install/tasks/pre_checks.yml
Labels: enhancement

#68 Fix missing info from 1809 example files
  documentation/ansible/system-design-deployment/examples/S4HANA_1809_SP5_v001/bom.yml
  documentation/ansible/system-design-deployment/examples/S4HANA_1809_SP5_v001/stackfiles/myDownloadBasketFiles.txt
Labels: bug

#67 App inifile generation testing document updates
  documentation/ansible/system-design-deployment/app/prepare-ini.md
  documentation/ansible/system-design-deployment/examples/S4HANA_1909_SP2_v001/stackfiles/bom.yml
Labels: documentation, enhancement
