Repository Centiq/sap-hana, pull requests merged in 2020-04, with the labels that each got.

#21 Backlog items copy global ini
  deploy/v2/ansible/roles/hana-system-replication/tasks/pre_checks.yml
  deploy/v2/ansible/roles/hana-system-replication/tasks/provision_hana_replication.yml
  deploy/v2/ansible/roles/hana-system-replication/tasks/set_global_ini_value.yml
  deploy/v2/ansible/roles/hana-system-replication/tasks/set_global_ini_values.yml
  deploy/v2/ansible/roles/hana-system-replication/vars/main.yml
Labels: enhancement

#23 Add Loadbalancer Frontend IP to the output JSON file
  deploy/v2/README.MD
  deploy/v2/input.json
  deploy/v2/template_samples/clustered_hana.json
  deploy/v2/template_samples/single_node_hana.json
  deploy/v2/terraform/main.tf
  deploy/v2/terraform/modules/hdb_node/main.tf
  deploy/v2/terraform/modules/hdb_node/variables_local.tf
  deploy/v2/terraform/modules/output_files/main.tf
  deploy/v2/terraform/modules/output_files/variables_local.tf
  templates/tempGen/template-daily.json
  templates/tempGen/template.json
Labels: enhancement

#22 Add the subscription id and tenant id to the output.json file for use by Ansible
  deploy/v2/terraform/modules/output_files/main.tf
Labels: enhancement

#24 Backlog items use synchronize
  deploy/v2/ansible/roles/hana-system-replication/tasks/copy_ssfs_keys.yml
  deploy/v2/ansible/roles/hana-system-replication/tasks/main.yml
  deploy/v2/ansible/roles/hana-system-replication/tasks/set_trust_relationship.yml
Labels: enhancement

#27 HANA DB backup on primary node only
  deploy/v2/ansible/roles/hana-system-replication/tasks/create_hana_backup.yml
  deploy/v2/ansible/roles/hana-system-replication/tasks/provision_hana_replication.yml
Labels: bug

#18 HANA VM OS Clustering on SLES
  deploy/v2/ansible/roles/hana-os-clustering/defaults/main.yml
  deploy/v2/ansible/roles/hana-os-clustering/tasks/main.yml
  deploy/v2/ansible/roles/hana-os-clustering/tasks/pre_checks.yml
  deploy/v2/ansible/roles/hana-os-clustering/tasks/provision.yml
  deploy/v2/ansible/roles/hana-os-clustering/templates/corosync.conf.j2
  deploy/v2/ansible/sap_playbook.yml
  deploy/v2/ansible/vars/ha-packages.yml
Labels: enhancement

#31 Specify sap os util script
  deploy/v2/USAGE.md
  deploy/v2/template_samples/single_node_hana.json
  deploy/v2/terraform/modules/common_infrastructure/main.tf
  util/common_utils.sh
  util/sap_os_offers.json
  util/set_sap_os.sh
Labels: documentation, enhancement

#34 Check that sap_user and sap_password have been set before applying Terraform builds
  util/common_utils.sh
  util/terraform_v2.sh
Labels: enhancement

#36 Backlog: Copy xsa key files
  deploy/v2/ansible/roles/hana-system-replication/tasks/copy_ssfs_key_path.yml
  deploy/v2/ansible/roles/hana-system-replication/tasks/copy_ssfs_keys.yml
  deploy/v2/ansible/roles/hana-system-replication/tasks/main.yml
  deploy/v2/ansible/roles/hana-system-replication/tasks/pre_checks.yml
  deploy/v2/ansible/roles/hana-system-replication/tasks/set_runtime_path_facts.yml
  deploy/v2/ansible/roles/hana-system-replication/vars/main.yml
Labels: enhancement

#30 Add option for RHEL OS clustering
  deploy/v2/USAGE.md
  deploy/v2/ansible/roles/hana-os-clustering/defaults/main.yml
  deploy/v2/ansible/roles/hana-os-clustering/tasks/cluster-RedHat.yml
  deploy/v2/ansible/roles/hana-os-clustering/tasks/cluster-Suse.yml
  deploy/v2/ansible/roles/hana-os-clustering/tasks/pre_checks.yml
  deploy/v2/ansible/roles/hana-os-clustering/tasks/provision.yml
  deploy/v2/ansible/roles/hana-os-clustering/templates/corosync.conf.j2
  deploy/v2/ansible/roles/hana-os-clustering/vars/main.yml
  deploy/v2/ansible/sap_playbook.yml
  deploy/v2/ansible/vars/ha-packages.yml
  deploy/v2/input.json
  deploy/v2/template_samples/clustered_hana.json
  deploy/v2/template_samples/single_node_hana.json
  deploy/v2/terraform/modules/hdb_node/variables_local.tf
  templates/tempGen/template-daily.json
  templates/tempGen/template.json
  templates/tempGen/v2-allNew-HA.json
  util/set_ha_cluster_pass.sh
Labels: enhancement
